[build]
  # Directory where your build output is located (for example, for create-react-app, it's typically 'build')
  publish = "build"

  # Command to build your site
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200