[build]
  # Directory where your build output is located
  publish = "dist"

  # Command to build your site
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
